# Generated by Django 3.2.8 on 2022-05-14 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("book_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_date",
                    models.DateTimeField(
                        validators=[reservations.validators.validate_date_from]
                    ),
                ),
                (
                    "to_date",
                    models.DateTimeField(
                        validators=[reservations.validators.validate_date_to]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Valid"), (0, "Cancelled")], default=1
                    ),
                ),
                (
                    "employees",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
            ],
        ),
    ]
