#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo $DIR
mysql -h $DATABASE_HOST -P $DATABASE_PORT -u root --password="$DATABASE_ROOT_PASSWORD"  << EOF
DROP DATABASE IF EXISTS ${DATABASE_NAME};
CREATE DATABASE ${DATABASE_NAME};
USE ${DATABASE_NAME};
DROP USER IF EXISTS ${DATABASE_USER}@${DATABASE_HOST};
FLUSH PRIVILEGES;
CREATE USER ${DATABASE_USER}@${DATABASE_HOST} IDENTIFIED BY '${DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'${DATABASE_HOST}';
GRANT ALL PRIVILEGES ON test_${DATABASE_NAME}.* TO '${DATABASE_USER}'@'${DATABASE_HOST}';
EOF